language: csharp
mono:
  - latest
  - 3.12.0
  - 3.10.0
  - 3.8.0
  - 3.2.8
  - 2.10.8
install:
  - nuget restore MonoStream.sln
script:
 - xbuild /p:DefineConstants=CI_BUILD /p:Configuration=Release solution-name.sln
 - mono bin/Debug/Mono/MonoStream.exe