language: csharp
mono:
  - 5.12.0
  - 5.10.0
  - 5.8.0
  - 5.4.1
  - 5.4.0
  - 5.2.0
  - 5.0.0
  - 4.8.1
  - 4.6.2
  - 4.6.0
  - 4.4.2
install:
  - nuget restore MonoStream.sln
script:
 - xbuild /p:DefineConstants=CI_BUILD /p:Configuration=Release MonoStream-Mono.csproj
 - mono bin/Debug/Mono/MonoStream.exe